---
- name: Install Python and dependencies
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  environment: "{{proxy_env}}"
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
    - python-mysqldb
...
